/* eslint-disable react/prop-types */
import React from 'react';
import Head from 'next/head';

import { GET_LIST } from '../utils/graphql/queries/pokemon';
import client from '../utils/graphql/apollo-client';
import getRandomInt from '../utils/graphql/randomNumber';

import '../styles/Home.module.css';

/** @jsxImportSource @emotion/react */
// eslint-disable-next-line no-unused-vars
import { css, keyframes } from '@emotion/react';

import Catch from './catch';

const Home = ({ data }) => {
  return (
    <div>
      <Head>
        <title>PokemonApp || Catch The Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Catch data={data} />
    </div>
  );
};

export async function getServerSideProps() {
  const { data } = await client.query({
    variables: {
      limit: 10,
      //maximal offset from pokeapi is 1117
      offset: getRandomInt(0, 1117),
    },
    query: GET_LIST,
    ssrMode: true,
  });
  return {
    props: { data },
  };
}

export default Home;
